@baseUrl = http://localhost:5144
@authToken =  eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsIm5hbWVpZCI6IjYwNThmNWY1LTk4MTEtMTFmMS1hOTczLTAwZjQ4ZDU5OTMyNSIsIm5iZiI6MTc4Njc4OTM1MCwiZXhwIjoxNzg2Nzg5NjUwLCJpYXQiOjE3ODY3ODkzNTAsImlzcyI6Im15LWFwaSIsImF1ZCI6Im15LWFwcCJ9.yXeLyNIinki5hXkswiWFA69S_FPMNfNSiEssUlR-dPyqsd7NSJJGnjgmiJQAggPaNAkk0uqzPwTqzjBuLa8IgQ

### Update User Billing Address


POST {{baseUrl}}/cart/cart
Authorization: Bearer {{authToken}}
Content-Type: application/json

[
  {
    "produitId": 1,
    "quantite": 1
  }
]

