
DROP DATABASE store;
CREATE DATABASE IF NOT EXISTS store;
USE store;



CREATE TABLE Localite(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    CodePostal INT,
    Ville VARCHAR(50),
    Province VARCHAR(50)
);


CREATE TABLE Adresse(
    Id INT PRIMARY KEY AUTO_INCREMENT, 
    rue VARCHAR(70),
    numero INT,
    boite VARCHAR(5),
    IdLocalite INT DEFAULT NULL,
    FOREIGN KEY (Idlocalite) REFERENCES Localite(id)
);



CREATE TABLE IF NOT EXISTS Users (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    Username VARCHAR(256) NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    Nom TEXT,
    Prenom TEXT,
    IsAdmin BOOLEAN DEFAULT FALSE,
    IdFacturation INT DEFAULT NULL,
    IdLivraison INT DEFAULT NULL,
    CreatedAt DATETIME(6) DEFAULT (UTC_TIMESTAMP()),
    UpdatedAt DATETIME(6) DEFAULT (UTC_TIMESTAMP()) ON UPDATE CURRENT_TIMESTAMP(6),
    FOREIGN KEY(IdFacturation) REFERENCES Adresse(Id),
    FOREIGN KEY(IdLivraison) REFERENCES Adresse(Id)
);
