CREATE DATABASE IF NOT EXISTS store;
USE store;

CREATE TABLE IF NOT EXISTS Users (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    Username VARCHAR(256) NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    Nom TEXT DEFAULT "",
    Prenom TEXT DEFAULT "",
    IsAdmin BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME(6) DEFAULT (UTC_TIMESTAMP()),
    UpdatedAt DATETIME(6) DEFAULT (UTC_TIMESTAMP()) ON UPDATE CURRENT_TIMESTAMP(6)
);